# Website settings
title: Experiences and Opinions
url: "https://bhalothia.io"

# Internal nav
nav:
  main:
    archive: "/archive"
    # blog: "/blog"
    projects: "/projects"
  archive:
    all: "/archive"
    tags: "/archive/tags"
    rss: "/feed.xml"

# Bio settings
name: "Virendra Singh Bhalothia"
slogan: "I'm a Systems Engineer with over a decade of experience working on various phases of SDLC and most prominently in treating Infrastructure as Code and Site Reliability Operations."
description: "My Tech Rants!"
thumbnail_path: "tdb.jpg"
website_repo_url: "https://github.com/bhalothia/bhalothia.github.io"

# URLs
contact_urls:
  linkedin:
    url: "https://uk.linkedin.com/in/bhalothia"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/bhalothia/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:virendra@bhalothia.io"
    label: "Email"
    value: "virendra@bhalothia.io"
    icon: "envelope-square"
  stackoverflow:
    url: "https://stackoverflow.com/users/2248697/bhalothia"
    label: "Stackoverflow"
    value: "https://stackoverflow.com/users/2248697/bhalothia"
    icon: "square"

# Jekyll build settings
paginate: 10
paginate_path: "/archive/page:num"
permalink: "/archive/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
rouge: pygments
timezone: 'Europe/London'

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-gist
  - kramdown-parser-gfm
  - kramdown
  