# Website settings
title: Experiences and Opinions
url: "http://bhalothia.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"

# Bio settings
name: "Virendra Singh Bhalothia"
slogan: "I'm a DevOps Strategist and Enabler. Currently helping organizations in their DevOps transformation journey via <a href='http://theremotelab.com' target='_blank'>TRL</a>."
description: "My experiences and opinions."
thumbnail_path: "tdb.jpg"
website_repo_url: "https://github.com/bhalothia/bhalothia.github.io"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/bhalothiaa"
    label: "Twitter"
    icon: "twitter-square"
    username: "@bhalothiaa"
  linkedin:
    url: "https://uk.linkedin.com/in/bhalothia"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/bhalothia/"
    label: "GitHub"
    icon: "github-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
rouge: pygments
timezone: 'Europe/London'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
