# Website settings
title: Experiences and Opinions
url: "https://bhalothia.io"

# Internal nav
nav:
  main:
    blog: "/blog"
    # speaking: "/speaking"
    projects: "/projects"
  blog:
    all: "/blog"
    # popular: "/blog/popular"
    tags: "/blog/tags"
    rss: "/feed.xml"

# Bio settings
name: "Virendra Singh Bhalothia"
slogan: "I'm a Systems Engineer based out of Germany. I have over a decade of experience working on various phases of SDLC and most prominently in treating Infrastructure as Code and Site Reliability Operations."
description: "My Tech Rants!"
thumbnail_path: "tdb.jpg"
website_repo_url: "https://github.com/bhalothia/bhalothia.github.io"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/bhalothiaa"
    label: "Twitter"
    icon: "twitter-square"
    username: "@bhalothiaa"
  linkedin:
    url: "https://uk.linkedin.com/in/bhalothia"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/bhalothia/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:virendra@bhalothia.io"
    label: "Email"
    value: "virendra@bhalothia.io"
    icon: "envelope-square"    

# Jekyll build settings
paginate: 10
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
rouge: pygments
timezone: 'Europe/London'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  